### ISSUE TITLE
Suggest to loosen the dependency on fuzzywuzzy

### ISSUE THREAD

**Issue by Agnes-U** [VumBleBot/odqa_baseline_code#115]
Hi, your project odqa_baseline_code(commit id: 45954be766e5f987bef18e5b8a2e47f1508742cd) requires "fuzzywuzzy==0.18.0" in its dependency. After analyzing the source code, we found that the following versions of fuzzywuzzy can also be suitable, i.e., fuzzywuzzy 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.17.0, since all functions that you directly (1 APIs: fuzzywuzzy.fuzz.ratio) or indirectly (propagate to 5 fuzzywuzzy's internal APIs and 3 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on fuzzywuzzy from "fuzzywuzzy==0.18.0" to "fuzzywuzzy>=0.7.0,<=0.18.0". This will improve the applicability of odqa_baseline_code and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on fuzzywuzzy?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by olenmg** [comment]
We're sorry for not getting back to you sooner. But sure! We always welcome any improvements.
And unfortunately, we haven't used any automatic tools for dependency analysis.
It would be helpful for maintaining, but we don't have any plan for introducing it.

**Comment by Agnes-U** [comment]
Thanks for your kind response! Here's the [PR](https://github.com/VumBleBot/odqa_baseline_code/pull/116).
