### ISSUE TITLE
<bug> topk의 개수에 상관없이 첫 번째 context만 사용하는 Issue

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/odqa_baseline_code#15]
https://github.com/VumBleBot/odqa_baseline_code/blob/392dab026537de37e079953ee6deaf8cb58206fc/retrieval/sparse/base_retrieval.py#L116-L127

122, 123 번 째 줄을 보면 여러 개의 문서를 반환해도 한 개의 문서만 사용하는 코드인 것을 확인할 수 있습니다.

**수정 건의 사항**

- topk 개의 문서를 반환받도록 수정하고
- post_processing에서 topk 개의 문서에서 정답을 출력하도록 수정

**Comment by olenmg** [comment]
말씀해주신대로 고쳐야할 것 같습니다!
근데 retriever에서 top-k개, 질문에서 top-k개를 각각 추출하면 결국 k^2개나 되버려서 이거 top-k개 추출은 그냥 retriever 디버깅이나 EDA용으로 활용하게 될 것 같은데 어떻게 생각하시나요? 물론 EDA/디버깅용으로만 쓴다고 해도 구현하는게 맞다고 봅니다

여담으로 123번째줄 주석에 오타 있어서 저것도 나중에 고쳐야할 것 같네요 ㅋ.ㅋ

**Comment by ggm1207** [comment]
질문에서 top-k가 뭘 의미하는 건지 알 수 있을까요?? :thinking:

저는 하나의 질문이 주어졌을 때, 그 질문 기반으로 문서를 topk개 만큼 찾아야 된다는 의미였습니다!

**Comment by olenmg** [comment]
제가 잘못 이해했던 것 같습니다 😹 오늘 회의때 내용 얘기했으니 이슈 닫아도 될 것 같아요!
