### ISSUE TITLE
[SUGGEST] evaluation.py 이전

### ISSUE THREAD

**Issue by olenmg** [VumBleBot/odqa_baseline_code#22]
## ✔️  추가하고싶은 기능

- 프로젝트에 덧붙이고 싶은 기능들을 제안합니다. 아래의 종류에 맞게 체크해주세요.

- [ ] Data
- [ ] Preprocessing
- [ ] Model
- [x] Feature
- [ ] Paper
- [ ] Serving
- [ ] ETC (ex - library, reference.

==========

기존 baseline code의 evaluation.py와 같은 역할을 하는 코드를(혹은 동일한 코드를) 저희 베이스라인에도 넣으려고 합니다.
실제 리더보드에서의 성능평가 방법과 동일 방식으로 최대한 정확한 validation score를 측정 및 저장하고자 합니다.

==========

---

## 📚  레퍼런스 첨부

- 해당 기능에 대한 정보를 어디서 알게되었는지 출처를 기록해주세요!
- 책, 블로그, 유튜브, 논문 등

---
## 📸  스크린샷 

- 해당 기능을 적용시켰을 때의 사례를 미리볼 수 있게 사진 등으로 첨부해주세요.

**Comment by SeongIkKim** [comment]
확인했습니다. 제가 오늘 늦은 오전부터 일정이 있는데 다시 새벽이나 되어서야 작업이 가능합니다 ㅠㅠ
그전까지 코드 보고 일단 ~~커밋 남겨두겠습니다.~~
기존 코드의 evaluation.py를 그대로 옮겨오되 ground_truth 파일을 형식에 맞춰 만들어서 모델 prediction시 나오는 predict 파일과 비교해야할까요?

**Comment by olenmg** [comment]
> 확인했습니다. 제가 오늘 늦은 오전부터 일정이 있는데 다시 새벽이나 되어서야 작업이 가능합니다 ㅠㅠ
> 
> 그전까지 코드 보고 일단 ~~커밋 남겨두겠습니다.~~
> 
> 기존 코드의 evaluation.py를 그대로 옮겨오되 ground_truth 파일을 형식에 맞춰 만들어서 모델 prediction시 나오는 predict 파일과 비교해야할까요?

앗 성익님 **이부분은 제가 처리할 예정입니다!** 어제 밤에 따로 줌에서 얘기했었는데 성익님이 안계셨어서 assign 해뒀습니다!
방향성은 말씀하신 내용과 일치하는 것 같습니다~
