### ISSUE TITLE
[BUG] BM25 관련 발견한 이슈들

### ISSUE THREAD

**Issue by olenmg** [VumBleBot/odqa_baseline_code#24]
## 🐞  버그 제보

1. `bm25.py`에 `sparse_base.py`에 구현되어있는 `get_embedding()` 메소드가 똑같이 구현되어있습니다.
2. 현재 `BM25Retriever`에서 생성되는 `embedding.bin`과 `BM25.bin`이 `BM25/`디렉토리에 들어가지 않습니다.
3. `prepare.py`에 `BM25Retriever`을 불러오기 위한 코드 구현이 안되어있습니다.
4. BM25 + mrc 돌리면 성능이 {'exact_match': 6.25, 'f1': 10.223824786324787, 'epoch': 3.0}로 슬랙에 올린 TFIDF의 성능보다 현저히 떨어집니다. 이건 근데 BM25의 문제인지 다른 문제인지 확인이 필요할 것 같습니다. 
5. (번외) `model_args.py`의 retriever_name의 default 값이 `tfidf`인데 현재는 tfidf를 `TFIDF`라는 이름으로 사용중입니다.

---

## 👣  버그 발견 과정

- train/eval 돌려보면서 발견했습니다

---

## 🤔  수정 방향

1. `bm25.py`의 `get_embedding`메소드 구현 삭제
2. 지금 얼핏 보기에는 `args.path.embed = p.join(args.data_path, "embed")`이고 `self.embed_path = p.join(args.path.embed, "embedding.bin")`로 들어가는 형태라서 이 부분을 `self.embed_path = p.join([args.path.embed, self.name, "embedding.bin"])` 뭐 이런식으로 들어가야 할 것 같습니다.
3. `prepare.py`의 `RETRIEVER`에 BM25Retrieval 추가하고 BM25Retrieval 모듈 import하면 됩니다.
4. 4번째 이슈의 경우 추가적인 확인이 필요할 것 같습니다 (이 부분은 아직 확인 안했습니다)
5. 이것도 그냥 `config/model_args.py` 고치면 됩니다.

**다른건 다 고쳤는데 4번 이슈만 아직 못 고쳤습니다! 확인해주시면 해당사항 반영하여 PR 넣겠습니다.**

---

## 📸   스크린샷 첨부

(2번이슈)
![image](https://user-images.githubusercontent.com/61135159/117043797-a4db0600-ad48-11eb-9fc6-128e795b5b8b.png)

---

## 🌏  환경 세팅

- OS, 라이브러리 버젼 등을 명시해주세요.

**Comment by ebbunnim** [comment]
종헌님, 1번에서 get_embedding은 `self.avdl = self.p_embedding.sum(1).mean()` 요 부분이 bm25.py에는 추가되어 있는 것 같아요!

**Comment by ebbunnim** [comment]
그리고 혹시 bm25.py 돌리시면, 소요되는 시간이 보통 얼마나 되시나요? 저는 멈춤상태로 지금 2분 넘게 있어서..

**Comment by olenmg** [comment]
> 종헌님, 1번에서 get_embedding은 `self.avdl = self.p_embedding.sum(1).mean()` 요 부분이 bm25.py에는 추가되어 있는 것 같아요!
> 
> 
> 
> 

앗 그러네요ㅋㅋㅋㅋ 아까 줌에서 얘기하신 부분같은데 그때 딴거 하고 있었어서 놓쳤나봐요ㅠㅠ 마침 아직 안지웠는데 다행이네요
