### ISSUE TITLE
<feature> debug 기능 추가

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/odqa_baseline_code#3]
**사용법**
```bash
python -m run --strategis ST01,ST02 --run_cnt 3 --debug true
python -m run --strategis ST01,ST02 --run_cnt 3 --debug True
```

**코드**
args.debug로 접근 가능.
debug: default 값은 False로 두고 True시에 아래 처럼 parameter 수정

**수정 해야 될 것들**
- epoch 1로 설정 ( run.py 반복문 안에서 )
- run_cnt 1로 설정 ( run.py 반복문 돌기 전에 )
- 학습 시에 datasets['train'] 5%만 사용하도록 코드 수정 ( prepare.py )

**기능 설명**
- 잘 돌아가는지 미리 체크해보는 기능

**Comment by ebbunnim** [comment]
[Update] --strategy > --strategis 로 수정했습니다.

**Comment by olenmg** [comment]
이거 혹시 strategis -> strategies로 바꿔도 되나요..?!

**Comment by ggm1207** [comment]
넵!
