### ISSUE TITLE
[TODO] (05.06) 현재 MRC 모델의 성능과 valid set

### ISSUE THREAD

**Issue by olenmg** [VumBleBot/odqa_baseline_code#32]
## 📌  요약

-  현재 베이스라인을 이용하여 `xlm-roberta-base`로 성능 측정하였습니다.

## 📔  상세

사실 아직 모델 하나 돌린거라 큰 의미는 없지만 `xlm-roberta-large`가 오류로 안돌아가서 `xlm-roberta-base`로 측정한 결과 먼저 공유드립니다. **evaluation.py로 평가된 지표 기준입니다.**

먼저 문서는 정답 문서로 고정시켜놓고 **MRC 모델만 돌렸을 때의 성능입니다.**
```json
{
    "EM": {
        "value": "47.08%",
        "rank": true,
        "decs": true
    },
    "F1": {
        "value": "67.94%",
        "rank": false,
        "decs": true
    }
}
```

다음으로 MRC 모델 + Retriever 모델 모두 돌렸을 때 기준입니다.
현재 validation 및 predict에서 top-k개를 가져오지 않기 때문에 top-1로 생각하시면 될 것 같고 Retriever는 TF-IDF 사용했습니다.

```json
{
    "EM": {
        "value": "21.67%",
        "rank": true,
        "decs": true
    },
    "F1": {
        "value": "36.00%",
        "rank": false,
        "decs": true
    }
}
```
문서만 어느정도 잘 가져온다면 EM 40% 정도는 넘을 수 있을 것 같습니다.

또한 이 모델로 prediction(LB 제출) 진행한 결과 **EM 23.75%, F1 38.74%** 얻었습니다.
이전에 튜닝 없이 진행했을 때 동일 백본(xlm-roberta-base)으로 **EM 12.92% F1 20.26%** 얻었던거 생각해보면 TF-IDF에서 max_features 없앤게 역시 주효했다고 볼 수 있을 것 같습니다. 
> 지금 당장 이전과 다른게 TF-IDF의 max_features 없앤거밖에 생각이 안나서 이렇게 생각했는데 혹시 다른거 달라진게 있다면 댓글로 부탁드립니다!

그리고 지금 validation의 score와 LB score가 거의 비슷한 것 같은데, 지금 당장 여러 모델을 돌려보지는 못해서 확신할 수는 없지만, **validation score도 의미있다고 생각**할 수 있을 것 같습니다.
이건 추후에 모델 더 돌려보고 관련한 정보 더 공유드릴게요!

지금까지 나온 스코어들을 보고 드는 생각은 
1. retriever는 top-k로 어느정도 스코어를 보정할 수 있으니 성능이 더 올라갈 수 있음. 
2. MRC 모델만으로 나오는 스코어가 생각보다 불안정함. 현재 47%/67%에서 더 개선할 다른 방법을 찾아보아야함.
**(수정) 생각해보니 MRC 모델도 epoch 더 돌리면 스코어 올라갈 수 있을 것 같네요! 현재는 3epoch 기준입니다.**

2번 문제의 경우 제가 읽기로한 논문 읽어보고 개선 방향 생각해보겠습니다.

### 05.07 수정 (xlm-roberta large 추가)
|       |     LB      | Eval-MRC+RT |  Eval-MRC   |
| :---: | :---------: | :---------: | :---------: |
| base  | 23.75/38.74 | **21.67**/36.00 | 47.08/67.94 |
| large | **27.92**/**44.63** | 21.25/**37.48** | **50.83**/**74.25** |

**Comment by sooyounlee** [comment]
TF-IDF가 topk=1일 때 22% 정도 성능인데, 거기서 MRC로 21%가 나온다는건 잘 가져오는건 거의 다 맞춘다는 말이네요! 아마 중요한 키워드들이 겹치는건 맞추기도 쉽나봐요!

**Comment by olenmg** [comment]
(추가) 제가 어제 밤에 돌려놓고 갔는데 MRC모델은 epoch 3이 epoch 10보다 성능이 더 좋은 것 같습니다ㅋㅋㅋ 단순히 에폭 늘려서 성능을 향상시키는데는 한계가 있는 것 같아요
