### ISSUE TITLE
[BUG] Trainer에 인자를 잘 못 넘겨주고 있었습니다..!!!

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/odqa_baseline_code#40]
## 🐞  버그 제보

```python
def get_trainer(self):
    trainer = QuestionAnsweringTrainer(
        model=self.model,
        args=self.args.train,
        custom_args=self.args,
        train_dataset=self.train_dataset,
        eval_dataset=self.eval_dataset,
        eval_examples=self.datasets["validation"],  # self.datasets로 넘겨주면 안됨.
        tokenizer=self.tokenizer,
        data_collator=self.data_collator,
        post_process_function=self._post_processing_function,
        compute_metrics=self._compute_metrics,
    )
```

self.datasets는 retrieve되기 전의 dataset이어서 top_k가 적용되지 않았습니다. ( 무조건 top-1 )

==========
- eval_examples에 retrieve 되기 전의 Data를 넘겨주고 있었습니다.
- top-k가 1일 때는 문제가 되지 않지만, top-k가 2 이상일 때는 context mapping이 제대로 되지 않습니다.

==========

---

## 👣  버그 발견 과정

- 후처리 부분을 직접 타이핑하다가 발견함.

## 🤔  원래 예상했던 결과

- 버그가 발생하기 이전, 내가 기대한 작동과정과 결과값의 형태를 간략히 서술해주세요.

---

## 📸   스크린샷 첨부

- 버그 발생 당시의 스크린샷을 첨부해주세요.

---

## 🌏  환경 세팅

- OS, 라이브러리 버젼 등을 명시해주세요.

**Comment by olenmg** [comment]
~이거 eval_examples를 위해 wrapping?을 해줘야할까요..?~
그대로 `self.eval_dataset` 넣어주면 해결될까요?

**Comment by ggm1207** [comment]
@olenmg 
```python
    def set_dataset(self, datasets, is_run=True):
        self.train_dataset = self.preprocess_dataset(self.datasets, is_train=True) if is_run else None
        self.eval_dataset = self.preprocess_dataset(datasets, is_train=False)
        self.retrieve_datasets = datasets
```
여기서 datasets['validation'] 을 넣어줘야 해요. 그래서 우선은 간단하게 이렇게 넘길까 생각중입니다.

```python
eval_examples=self.retrieve_datasets["validation"],
```

**Comment by olenmg** [comment]
> @olenmg
> 
> ```python
>     def set_dataset(self, datasets, is_run=True):
>         self.train_dataset = self.preprocess_dataset(self.datasets, is_train=True) if is_run else None
>         self.eval_dataset = self.preprocess_dataset(datasets, is_train=False)
>         self.retrieve_datasets = datasets
> ```
> 
> 여기서 datasets['validation'] 을 넣어줘야 해요. 그래서 우선은 간단하게 이렇게 넘길까 생각중입니다.
> 
> ```python
> eval_examples=self.retrieve_datasets["validation"],
> ```

이거 성익님께서도 말씀해주셨던건데, 데이터셋 처리 관해서 뭔가 깔끔하게 처리할 필요가 있을 것 같아요
`run.py`, `base_reader.py` 쪽에 데이터셋 불러오는거 관련해서 중복된 로직이 좀 있는것같기도 하고.. 일단 한번 고민해볼게요!

**Comment by ggm1207** [comment]
맞아여.. 사실 self.datasets 덮어 씌울까하다가 혹시 몰라서 새로 만들었습니다 :crying_cat_face: 코드 리팩토링은 언제든 환영입니다! :smile:
