### ISSUE TITLE
[TODO] DashBoard 제작

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/odqa_baseline_code#44]
## 📌  요약

- (수행 전) Bokeh 를 사용한 Dash Board 제작

- (수행 후) 결과는 어땠는지

### Before
- embedding.bin
- wiki dataset
- top k 데이터

이 세 가지를 잘 결합하면 Retriever 분석에 큰 도움이 될 것 같습니다! 필요한 기능 있으시면 댓글 달아주세요
- EX) 틀린 정답들의 문서 별 길이 보여주는 기능. 

### After

-

**Comment by SeongIkKim** [comment]
개인적으로 어떻게 하는건지 정말 궁금하네요... 나중에 작업하실때 공유받거나 참여하고싶습니다!

**Comment by sooyounlee** [comment]
오 이 dashboard가 어떤 기능이 있는지 궁금하네요!
우선 있었으면 좋겠는거 상상의 나래를 펼쳐보자면..

틀리게 뽑힌 지문들 query와 겹치는 부분 highlight해서 보여주기 (혹은 많이 겹친 문장? 추출해서 보여주기?)
틀린 query들 tokenizing이 어떻게 되는지 보여주기
top-k개 지문들의 score, 평균, 표준편차

**Comment by ggm1207** [comment]
> 오 이 dashboard가 어떤 기능이 있는지 궁금하네요!
> 우선 있었으면 좋겠는거 상상의 나래를 펼쳐보자면..
> 
> 틀리게 뽑힌 지문들 query와 겹치는 부분 highlight해서 보여주기 (혹은 많이 겹친 문장? 추출해서 보여주기?)
> 틀린 query들 tokenizing이 어떻게 되는지 보여주기
> top-k개 지문들의 score, 평균, 표준편차

넵, 우선 최대한 기능 넣어서 만들어보고 `Retriver`쪽 작업하시는 분들한테 더 여쭤봐서 기능 추가 할 생각입니다! 내일 피드백 부탁드려요!
