### ISSUE TITLE
[BUG] run_mrc.py 실행 시 context_id key error 발생

### ISSUE THREAD

**Issue by olenmg** [VumBleBot/odqa_baseline_code#47]
## 🐞  버그 제보

- 메인 브랜치 기준
- 현재 run_mrc를 debug 모드로 돌리면 evaluation 과정에서 'context_id'로 key error 발생합니다.
- 다른 분들도 동일 에러 발생하시는지 궁금합니다. 제 브랜치가 방금 좀 꼬였어서 제 로컬 코드 문제인지도 봐야할 것 같습니다.

---

## 👣  버그 발견 과정

- `python -m run_mrc --strategies ST01 --debug True --report False --run_cnt 1`로 실행
- README의 config와 동일 전략 사용

## 🤔  원래 예상했던 결과

- 
---

## 📸   스크린샷 첨부

![image](https://user-images.githubusercontent.com/61135159/117543708-e32e3900-b058-11eb-9229-8531033f3dec.png)

---

## 🌏  환경 세팅

- OS, 라이브러리 버젼 등을 명시해주세요.

**Comment by SeongIkKim** [comment]
ㅠㅠ 저도 확인해보니까 제가 고친 postprocess 부분에서 추후에 분석을 위해서 context_id를 prediction에 넣어놓도록 해서 그렇습니다. eval 데이터셋에서는 괜찮은데 do_predict할때 test dataset에서는 context와 context_id가 없어서 키에러가 납니다.
[링크](https://github.com/VumBleBot/odqa_baseline_code/blob/8367c972782da35898a796dc1d57a922ca5f9922/utils_qa.py#L202-L203)
이파트인데, 이 부분 부가적으로 추가한거라 지우시고 시도하시면 정상적으로 작동할겁니다.

**Comment by olenmg** [comment]
> ㅠㅠ 저도 확인해보니까 제가 고친 postprocess 부분에서 추후에 분석을 위해서 context_id를 prediction에 넣어놓도록 해서 그렇습니다. eval 데이터셋에서는 괜찮은데 do_predict할때 test dataset에서는 context와 context_id가 없어서 키에러가 납니다.
> [링크](https://github.com/VumBleBot/odqa_baseline_code/blob/8367c972782da35898a796dc1d57a922ca5f9922/utils_qa.py#L202-L203)
> 이파트인데, 이 부분 부가적으로 추가한거라 지우시고 시도하시면 정상적으로 작동할겁니다.

넵 그리고 `retriever.retrieve()` 돌릴 때 `context_id` key가 추가되고 있어서, `run_mrc` 돌릴 때도 에러가 나는 것 같아요
`run_mrc`에서는 `retriever.retrieve()`를 안해서  `context_id`가 추가 안되고 있거든용 retrieve 없이 바로 original context에서 mrc를 해서 에러가 나는 것 같습니다.

근데 해당 부분 지워도 상관 없는걸까요? 아직 그 부분이 어떤 역할을 하는지 못읽어본 상태라서요 !

**Comment by SeongIkKim** [comment]
제가 run_mrc 기준으로 테스트를 안하고 run 기준으로 테스트했어서 그렇네요. 주석처리해도 되는게 nbest prediction 뽑아낼 때 어떤 context와 context_id에서 해당 예측이 나왔는지 json 파일에 기록하는 용도로 넣어놨습니다. 이부분은 제가 지금 버그픽스해서 올리도록 하겠습니다!

**Comment by olenmg** [comment]
> 제가 run_mrc 기준으로 테스트를 안하고 run 기준으로 테스트했어서 그렇네요. 주석처리해도 되는게 nbest prediction 뽑아낼 때 어떤 context와 context_id에서 해당 예측이 나왔는지 json 파일에 기록하는 용도로 넣어놨습니다. 이부분은 제가 지금 버그픽스해서 올리도록 하겠습니다!

봤는데 이게 생각보다 건드릴게 조금씩 있네요.. (**run_mrc 기준**)
현재 상태로는 validation 240개에서 topk=5라고 하면 predictions를 48개 내놔서 topk=1로 줄때만 predictions을 제대로 내놓습니다ㅠ

해결 방법은
1) utils_qa.py에서 해당부분 잘 처리 (내부를 잘 몰라서.. 일단 이렇게 써둡니다) 
2) run_mrc 모듈 내에서 args.retriever.topk=1로 수동 처리

제가 보기엔 2번이 편할 것 같습니다 ,, 1번에서 쉽게 처리 되면 1번에서 해도 괜찮을 것 같구요
어떻게 생각하시나용??

**Comment by SeongIkKim** [comment]
utils_qa에서 prediction을 k개로 묶어서 내놓는건 postprocess 이전에 retrieve로 dataset을 topk로 뻥튀기 한 뒤에 진행합니다.  말씀하신대로 리더 모델 성능만 평가하기위해 run_mrc 모듈 내부에서 topk=1로 제한하는게 편할 것 같습니다 ㅠㅠ config파일 기준으로 topk를 나누도록 되어있어서 유저가 run_mrc 돌릴때마다 수동으로 config의 topk를 1로 조작하는것보다는 그게 나을것같아요.
디버깅 감사합니다 종헌님!

**Comment by olenmg** [comment]
> utils_qa에서 prediction을 k개로 묶어서 내놓는건 postprocess 이전에 retrieve로 dataset을 topk로 뻥튀기 한 뒤에 진행합니다.  말씀하신대로 리더 모델 성능만 평가하기위해 run_mrc 모듈 내부에서 topk=1로 제한하는게 편할 것 같습니다 ㅠㅠ config파일 기준으로 topk를 나누도록 되어있어서 유저가 run_mrc 돌릴때마다 수동으로 config의 topk를 1로 조작하는것보다는 그게 나을것같아요.
> 
> 디버깅 감사합니다 종헌님!

넵 일단 자야돼서 방금 일단은 그렇게 해서 PR 넣어놨는데 다행이네요
연이틀 늦은 밤까지 고생하십니다...😭
