### ISSUE TITLE
[TODO] slack 포함 api key값 분리

### ISSUE THREAD

**Issue by SeongIkKim** [VumBleBot/odqa_baseline_code#57]
## ✔️  추가하고싶은 기능

- 프로젝트에 덧붙이고 싶은 기능들을 제안합니다. 아래의 종류에 맞게 체크해주세요.

- [ ] Data
- [ ] Preprocessing
- [ ] Model
- [ ] Feature
- [ ] Paper
- [ ] Serving
- [x] ETC (ex - library, reference)

==========

`slack_api.py`를 포함해 혹시 추후에 api를 사용하는 환경에서 token이나 secret_key가 필요할 경우 github에 올라가지 않도록. input 디렉토리 아래에 secret.json을 따로 두어 key 및 token 값을 관리하고자 합니다.

단순히 같은 디렉토리에 숨김파일로 만들고 .gitignore로 처리해도되겠지만 의미상 input 디렉토리 아래에 두는게 좋을 것 같습니다!
괜찮으시면 기존 PR merge 이후에 제가 PR 날리겠습니다.

==========

---

## 📚  레퍼런스 첨부

- 해당 기능에 대한 정보를 어디서 알게되었는지 출처를 기록해주세요!
- 책, 블로그, 유튜브, 논문 등

---
## 📸  스크린샷 

- 해당 기능을 적용시켰을 때의 사례를 미리볼 수 있게 사진 등으로 첨부해주세요.

**Comment by olenmg** [comment]
너무 좋아요!!
.gitignore에 넣고 파일 만들 생각했었는데 그냥 input에 넣는게 훨씬 좋을것같아요
