### ISSUE TITLE
[QA] GPU 연결 끊김현상 미치겠습니다...

### ISSUE THREAD

**Issue by ebbunnim** [VumBleBot/odqa_baseline_code#63]
##  📸  코드

- 학습을 시작하기 전에 연결 끊기는 현상
<img width="1039" alt="스크린샷 2021-05-12 오전 9 42 49" src="https://user-images.githubusercontent.com/46434838/117917310-c24d3880-b323-11eb-9a6c-8e36daa4faa4.png">

- 학습 중에 갑자기 연결 끊기는 현상
<img width="513" alt="스크린샷 2021-05-12 오후 1 10 17" src="https://user-images.githubusercontent.com/46434838/117917350-d8f38f80-b323-11eb-80ac-dd5ee53fb81d.png">

정말.... 제가.... 뭘 잘못하고 있는 걸까요?????
왜 제가 학습을 돌리기만 하면 이렇게 이슈들이 있을까요. run_retrieval, run 모두에 해당하는 이슈들입니다 ㅠㅠ

**Comment by SeongIkKim** [comment]
remote 서버와 connection은 평소에 정상적으로 작동하나요?

**Comment by ebbunnim** [comment]
> remote 서버와 connection은 평소에 정상적으로 작동하나요?

접속이 time out으로 안되는 경우도 있고, 위에 처럼 학습하다가 끊기는 경우 모두 있습니다 ㅠㅠ

**Comment by SeongIkKim** [comment]
며칠 전부터 서버 커넥션이 안좋은 오류가 있다고 하던데, 운영진분께는 문의해보셨나요?

**Comment by ebbunnim** [comment]
> 며칠 전부터 서버 커넥션이 안좋은 오류가 있다고 하던데, 운영진분께는 문의해보셨나요?

문의해볼게요.. 아무래도 서버 새로 할당받아야 하나봐요... 근데 서버 새로 받으려면 기존의 서버는 먼저 닫아야 하나요?

**Comment by SeongIkKim** [comment]
저는 지금까지는 닫고 받았었는데, 닫으면 열어주시기전까지 서버 할당을 못받는 경우가 있어서 일단 문의부터 먼저 드리는게 좋을것같아요.

**Comment by ebbunnim** [comment]
> 저는 지금까지는 닫고 받았었는데, 닫으면 열어주시기전까지 서버 할당을 못받는 경우가 있어서 일단 문의부터 먼저 드리는게 좋을것같아요.

넵 감사합니다! ㅠㅠ
