### ISSUE TITLE
[QA/REVIEW] 비슷한 정답을 LB스코어에서 EM으로 인정하는가?

### ISSUE THREAD

**Issue by SeongIkKim** [VumBleBot/odqa_baseline_code#68]
##  📸  코드

1. 테스트데이터셋 mrc-0-002191

![Screen Shot 2021-05-13 at 11 52 52 AM](https://user-images.githubusercontent.com/26772420/118070917-c0e24580-b3e1-11eb-8095-bda257e37f49.png)
![Screen Shot 2021-05-13 at 11 53 06 AM](https://user-images.githubusercontent.com/26772420/118070936-c93a8080-b3e1-11eb-99db-8f8d306a5ea9.png)

정답(추측) : 빌헬름 미클라스

기존의 prediction : 대통령인 빌헬름 미클라스

- 빌헬름 미클라스로 바꾸고 제출했을때
    - EM : 32.08% → **32.50%**
    - F1 : 43.34% → **43.44%**

2. 테스트 데이터셋 mrc-0-002169

![Screen Shot 2021-05-13 at 11 54 04 AM](https://user-images.githubusercontent.com/26772420/118071023-ecfdc680-b3e1-11eb-8390-1b3458281d6f.png)
![Screen Shot 2021-05-13 at 11 54 17 AM](https://user-images.githubusercontent.com/26772420/118071038-f424d480-b3e1-11eb-96d1-eaf82de760e2.png)

정답(추측) : 다케다 한시, 다케다 한시(武田範之)

기존의 prediction : 다케다 한시(武田範之)

- 다케다 한시로 바꾸고 제출했을때
    - EM : 32.08% → **31.67%**
    - F1 : 43.34% → **43.22%**

3. 테스트 데이터셋 mrc-0-000898

![Screen Shot 2021-05-13 at 11 54 47 AM](https://user-images.githubusercontent.com/26772420/118071078-056de100-b3e2-11eb-98ae-e5ccd30dde9b.png)
![Screen Shot 2021-05-13 at 11 55 00 AM](https://user-images.githubusercontent.com/26772420/118071097-0ef74900-b3e2-11eb-95be-b31b11465654.png)

정답(추측) : 이회창, 이회창 후보

기존의 prediction : 이회창 후보

- 이회창으로 바꾸고 제출했을때
    - EM : 32.08% → **31.67%**
    - F1 : 43.34% → **43.24%**

<img width="471" alt="Screen Shot 2021-05-13 at 11 56 01 AM" src="https://user-images.githubusercontent.com/26772420/118071163-34845280-b3e2-11eb-8096-7545e7b94732.png">

---

## 🤔  궁금한 점

- **생각보다 정답 기준이 빡빡합니다. 동일한 맥락/동일한 의미의 단어라도 호칭 등이 붙지 않으면 EM 스코어가 찍히지 않습니다.**
  - 비슷한 단어를 정답으로 인정해주는 경우는 "<중앙일보>" == "중앙일보" 정도일것같습니다.
- reader 모델이 어떻게 해야할까요?
  - 정답 단어를 살펴보면 정확히 질문의 답변에 해당하는 문장에서 나온 단어임을 알수 있습니다(ex- `이회창` 대신 `이회창 후보`).
  - reader 모델이 정답을 뽑을 때 context 전체에서 답변을 뽑아내지말고, context에서 정답이 들어있을법한 문장을 logit값으로 뽑은 뒤 그 내부에서 정답을 찾아내도록 하는건 어떨까요?
    - 이렇게 되면 정답이 들어있을법한 문장도 k개(혹은 j개)를 뽑아야 할까요?

---

## 📚  레퍼런스 첨부

- 의문 해결에 도움을 주는 참고 문헌이 있다면 기록해주세요!
- 책, 블로그, 유튜브, 논문 등

**Comment by olenmg** [comment]
😥 😥 😥 😥 😥 😥 😥 😥 😥 😥 😥
문장 뽑아서 하는 것도 좋긴한데 정답 문장 위치에 대한 라벨이 없어요ㅠㅠ
아 채점기준 너무한데요...👿
