### ISSUE TITLE
[TODO] ColBERT 구축, Dense Retriever

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/odqa_baseline_code#80]
## 📌  요약

- (수행 전) Token 수준의 Interaction을 하는 Dense Retriever를 구축합니다.

- (수행 후) TOP-3 90%인데 이걸 굳이? 라는 느낌이 드네요..

### Before

- https://github.com/stanford-futuredata/ColBERT
    - 이 곳을 참고해서 작업

### After

- Token Level의 상호작용이란, Token dim의 크기에 따라서 Size가 더 커질 수 있다는 걸 의미한다는 사실을... 깨닫지 못했습니다. ㅠ 
    - Embedding 하나에 15G 사용
    - 성능만 좋다면 미리 Test Dataset에 Validation을 결합하는 방식도 좋을 것 같습니다.

**Comment by sooyounlee** [comment]
오 SPARTA 논문이 token level interaction이라고 해서 어떻게 구현하나 궁금했는데 마침 비슷한 모델이 있었네요!!

**Comment by ggm1207** [comment]
> 오 SPARTA 논문이 token level interaction이라고 해서 어떻게 구현하나 궁금했는데 마침 비슷한 모델이 있었네요!!

넵넵, 수연님이 추천하기 전에 Survey 논문 보고 ColBERT 시작했는데 그 파트에 SPARTA 논문도 있더라구요. 근데 SPARTA는 어려워 보여서 ColBERT로 시작했습니다 ㅋㅋ
